language: php

os:
  - linux

dist: "xenial"

jobs:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3_VERSION=^9
    - php: 7.2
      env: TYPO3_VERSION=^8
    - php: 7.1
      env: TYPO3_VERSION=^8
    - php: 7.0
      env: TYPO3_VERSION=^8
addons:
  apt:
    packages:
      - parallel

cache:
  directories:
  - "$HOME/.composer/cache"

before_install:
  - composer self-update
  - composer --version

install:
  - >
    if [[ "$TYPO3_VERSION" == "^8" ]];
    then
      composer require --no-update "typo3/cms:$TYPO3_VERSION"
    else
      composer require --no-update "typo3/minimal:$TYPO3_VERSION"
    fi
  - composer require --no-update "solarium/solarium"
  - composer install --prefer-dist
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
